# Biais {#sec-biais}

Un biais est une erreur [prévisible]{.cb1}, qui se produit systématiquement dans une [direction prédéterminée]{.cb1}.
C'est pour cette raison qu'elle est qualifiée d'erreur [systématique]{.cb1}.

Les biais ont pour conséquences :

- Une [diminution]{.cb1} de la capacité à [détecter une différence ou une association]{.cb1} significative si celle-ci existe réellement
- Une [sous-estimation ou une surestimation]{.cb1} de l'association entre les facteurs étudiés et la maladie

Il existe trois grandes catégories de biais :

- Biais de [sélection]{.cb1} 
- Biais de [classement]{.cb1} 
- Biais de [confusion]{.cb1}

Alors que la fluctuation d'échantillonnage est une erreur d'origine statistique, le biais est une erreur d'origine [méthodologique]{.cb1} : il affecte la [validité]{.cb1} d'une mesure et n'est [pas dépendant de la taille de l'échantillon]{.cb1}.

Une manière de s'en prémunir est donc d'élaborer une méthode, [une réflexion préalable]{.cb1} qui sera différente selon le contexte et le type de biais.


## Biais de sélection {#sec-biais-sel}

Un [biais de sélection]{.cb1} conduit *in fine* à une situation dans laquelle l'échantillon [n'est plus représentatif]{.cb1} de la population cible.

Il peut survenir à différentes étapes de la constitution d'une enquête, notamment lors de la formation de la [population source]{.cb1}, de l'[échantillonnage]{.cb1}, ou pendant le [suivi]{.cb1} dans les enquêtes de cohortes. 

- [Population source]{.cb1} 
: La population de laquelle est issu l'échantillon n'est pas représentative de la population cible. Cela peut être dû à une sélection spécifique de lieux de recrutement, comme les hôpitaux ou les cliniques, qui ne reflètent pas la diversité des conditions de la population générale.

::: callout-tip
## Critères d'inclusion ou d'exclusion trop restrictifs
Si une étude sur le diabète exclut les patients ayant des comorbidités, comme les maladies cardiovasculaires, les résultats ne seront [pas applicables]{.cb1} à de nombreux patients diabétiques qui vivent effectivement avec ces comorbidités.
:::

::: callout-tip
## Zone géographique restreinte
Une étude menée dans une région urbaine, où l'accès aux services de santé est facilité, pourrait [ne pas refléter]{.cb1} la situation des zones rurales ou moins développées.
:::

- [Échantillon]{.cb1}
: La participation des sujets à une étude nécessite un consentement actif : les sujets qui choisissent de participer peuvent différer systématiquement de ceux qui refusent, que ce soit en termes de caractéristiques démographiques ou comportementales, ou d'autres facteurs de risque pertinents pour l'étude.

::: callout-tip
## Lors de l'inclusion : les non-participants diffèrent des participants

Si les personnes plus malades ou ayant un niveau socio-économique inférieur sont moins susceptibles de participer à l'étude, les résultats peuvent [sous-estimer]{.cb1} l'association entre les facteurs de risque étudiés et la maladie.

La comparaison des participants et des non-participants peut aider à identifier et mesurer l'impact de ce manque sur la validité des résultats.
:::

::: callout-tip
## Lors du suivi : les sujets perdus de vue diffèrent des sujets restants

Les participants peuvent quitter l'étude pour diverses raisons (e.g., déménagement, décès, perte d'intérêt).

Si les participants restant dans l'étude ont un meilleur état de santé général que les perdus de vue, cela peut conduire à une [sous-estimation]{.cb1} des risques associés aux facteurs étudiés.

La comparaison des caractéristiques des sujets restants et des perdus de vue permet de mesurer l'impact de cette perte sur la validité des résultats.
:::

::: callout-warning
## La sélection n'engendre pas systématiquement un biais
À condition que l'objectif de l'étude soit clairement défini et que des méthodes appropriées soient utilisées pour ajuster l'impact de cette sélection.
:::


## Biais de classement

Un [biais de classement]{.cb1} (ou biais de mesure) survient au moment du [recueil de données]{.cb1}, lorsqu'il y a une erreur dans la façon dont l'exposition ou la maladie est mesurée.

Il conduit à des [erreurs de classement]{.cb1} des sujets dans les catégories pertinentes telles que malades/non malades ou exposés/non exposés.

::: callout-tip
## Déclaration de la consommation de tabac
Si les sujets participants à une étude ont systématiquement tendance à sous-estimer leur consommation de tabac, l'association entre le tabagisme et le cancer du poumon pourra être [faussement sous-estimée]{.cb1}.
:::

::: callout-tip
## Mesure de la température (partie III)
L'erreur de mesure induite par le mauvais calibrage du thermomètre est un biais de classement.

Le thermomètre est [biaisé]{.cb1} : à chaque mesure, il [surestime systématiquement]{.cb1} la vraie valeur de température chez votre patient.
:::

Le contrôle des biais de classement nécessite un [contrôle rigoureux de la mesure]{.cb1} (e.g., méthodes objectives, examens et questionnaires standardisés, calibrage du matériel).

## Biais de confusion {#sec-biais-conf}

Les biais de confusion sont liés à l'intervention d'un ou de plusieurs tiers facteurs (appelés [facteurs de confusion]{.cb1}).

En épidémiologie descriptive, ils peuvent intervenir lors de la [comparaison]{.cb1} d'indicateurs provenant de populations différentes.

::: callout-tip
## Comparaison des taux bruts de mortalité entre le Nord et la Creuse

Le Nord est un département plutôt jeune ; la Creuse est un département plutôt âgé. 

La structure d'âge est donc à l'origine un biais de confusion dans la comparaison de taux bruts de mortalité. On dit que c'est un [facteur de confusion]{.cb1}.

Il s'agit bien d'une erreur prévisible ayant une direction prédéterminée : un âge plus élevé est systématiquement associé à un taux de mortalité plus élevé.

Il existe une méthode pour s'affranchir de ce biais : la [standardisation]{.cb1} (@sec-stand).
:::

Les biais de confusion interviennent surtout lorsqu'on recherche des [causes]{.cb1} : ils sont donc particulièrement redoutés en [épidémiologie analytique]{.cb1}.

::: callout-tip
## Association entre port du briquet et cancer du poumon

On peut faire l'observation que les personnes portant un briquet sur elles ont plus de risque de développer un cancer du poumon.

Pour autant, peut-on dire que le port du briquet est la cause du cancer ? Probablement pas, puisqu'il existe dans cette association un tiers facteur : [le tabagisme]{.cb1}.

La tabagisme joue ici le rôle de [facteur de confusion]{.cb1} : il est à la fois lié au fait de porter un briquet sur soi et à la survenue du cancer du poumon.
:::

---
\

::: {.p style="text-align:center"}
## À RETENIR {.unnumbered .unlisted}
:::

::: callout-important
# Biais = erreurs systématiques
:::

::: callout-important
# Ils affectent la validité d'une mesure
:::

::: callout-important
# Ils ne sont pas modifiés par la taille de l'échantillon
:::

::: callout-important
# Ils peuvent être évités ou réduits avec une réflexion préalable
:::
