project:
  type: book

book:
  title: Épidémiologie descriptive
  description: "| **IFSI 1A - UE 1.2-S2 Santé Publique**"
  author: Université de Lille
  date: last-modified
  downloads: [pdf, docx]
  repo-url: https://codeberg.org/hebstr/epi_d
  sidebar:
    style: floating
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - 01-definitions.qmd
    - part: Indicateurs de santé
      chapters:
        - 02-indic_base.qmd
        - 03-indic_mort.qmd
        - 04-indic_morbi.qmd
    - part: Sources des indicateurs
      chapters:
        - 05-sources_base.qmd
        - 06-sources_spe.qmd
        - 07-sources_quali.qmd
    - part: Erreurs de mesure
      chapters:
        - 08-erreur_def.qmd
        - 09-erreur_fluct.qmd
        - 10-erreur_biais.qmd

format:
  hebstr-template-html: default
  # hebstr-template-typst: default

comments:
  hypothesis: true
