project:
  type: book

lang: fr

book:
  title: "**Épidémiologie descriptive**"
  description: "| **IFSI 1A - UE 1.2 Santé Publique**"
  author: Université de Lille
  date: today
  sidebar: 
    border: true
    background: secondary
  comments: 
    hypothesis:
      openSidebar: false
  chapters:
    - index.qmd
    
    - definitions.qmd
    
    - part: Indicateurs de santé
      chapters: 
        - indic_base.qmd
        - indic_mort.qmd
        - indic_morbi.qmd
    
    - part: Sources des indicateurs
      chapters: 
        - sources_base.qmd
        - sources_spe.qmd
        - sources_quali.qmd
    
    - part: Erreurs de mesure    
      chapters: 
        - erreur_def.qmd
        - erreur_fluct.qmd
        - erreur_biais.qmd
        
knitr: 
  opts_chunk:
    collapse: true
    comment: "#>"
    echo: false
    message: false
    warning: false

format:
  html:
    theme:
      light: 
        - cosmo
        - theme.scss
    callout-appearance: simple
    lightbox: true
    code-link: true
    code-copy: false
    code-fold: true
    reference-location: margin
