# Présentation {.unnumbered}

## Important {.unnumbered}

Le texte [souligné]() peut renvoyer soit à une autre partie du cours (chapitre, section, figure, ...), soit à un lien externe.

Les liens externes au cours sont présentées en tant que compléments au cours. 
Autrement dit, [tout de ce qui est demandé de connaitre pour l'examen est écrit dans ce cours]{.cb1}.

Il n'est pas demandé de connaitre de listes, de chiffres ou de formules mathématiques.

## Encadrés {.unnumbered}

En parcourant le cours, vous rencontrerez différents types d'encadrés ayant chacun une signification précise :

::: callout-note
## Une note/remarque
:::

::: callout-tip
## Un exemple
:::

::: {.callout-caution collapse="true" appearance="minimal"}
## Un énoncé ou une question (cliquer pour afficher la réponse)
La réponse
:::

::: callout-warning
## Une précision sur une notion de cours pouvant porter à confusion
:::

::: callout-important
## Ce qu'il est important de retenir du chapitre (placé en fin de chapitre)
:::

## Formats {.unnumbered}

## Barre de recherche {.unnumbered}

## Annotations {.unnumbered}



