# Mesures de base

### Qu'est-ce qu'un indicateur ? {.unnumbered}

Un indicateur de santé est une variable que l'on mesure afin de mesurer l'état de santé d'une population 

- Outil d'évaluation et d'aide à la décision 
- Permet de décrire l'état de santé des individus d'une communauté
- Bien définir ce que nous mesurons +++ : TEMPS-ESPACE-PERSONNE
- Toute mesure a un numérateur et un dénominateur


sont à la base de 2 grandes catégories d'indicateurs de santé :

- Les indicateurs de [mortalité]{.cb} (@sec-mrt)
- Les indicateurs de [morbidité]{.cb} (@sec-mrb) 


## Proportion {#sec-prop}

Une [proportion]{.cb} (ou [fréquence]{.cb}) est un rapport dans lequel le numérateur est inclus dans le dénominateur.

Il s'exprime en pourcentage ou en chiffre décimal compris entre 0 et 1.

::: callout-tip
## En 2023, sur 750 000 enfants de 24 mois, 600 000 sont correctement vaccinés contre la rougeole.

La proportion correspondante est $\frac{600 \ 000}{750 \ 000} = 0.8$ \
La couverture vaccinale contre la rougeole chez les enfants de 24 mois est de 80%.
:::

## Taux {#sec-taux}

Un taux est le risque de survenue d'un évènement au cours d'une période. Il s'exprime en pourcentage ou en chiffre compris entre 0 et 1.

Notion de temps et de risque

$$
\mathrm{
\frac
{Nombre \ d'évènements \ pendant \ une \ durée \ T}
{Nombre \ de \ sujet \ à \ risque \ de \ faire \ l'évènement \ pendant \ cette \ durée \ T}
}
$$

::: callout-tip
## Dans une maternelle, sur 200 enfants n'ayant jamais eu la varicelle et non vaccinés, il y a eu 72 nouveaux cas durant l'année scolaire 2021-2022.
:::

## Ratio 

Un ratio est un rapport des effectifs entre [deux modalités d'une variable binaire]{.cb}.

Ces modalités sont mutuellement exclusives : contrairement à une proportion, le numérateur ne peut pas être inclus dans le dénominateur (et inversement).

C'est un rapport [sans unité]{.cb}.

::: callout-tip
## En admettant que le sexe est une variable binaire (homme/femme), le "sex ratio" correspond au rapport du nombre d'hommes sur le nombre de femmes (ou inversement)

- Le sex ratio du diabète de type II est de 3 hommes pour 1 femme (3:1) : cette maladie concerne 3 fois plus souvent les hommes que les femmes.
- Le sex ratio de l'anorexie mentale est 1:9 : cette maladie concerne 9 fois plus souvent les femmes que les hommes.
:::


## Indice

Un indice est le rapport entre deux effectifs de [nature différente]{.cb}.

::: callout-tip
## 30 enfants sont hospitalisés dans un service de pédiatrie. Dans ce service, il y a 3 IDE.

Il y a ici deux effectifs de nature différente :

- Le nombre d'enfants
- Le nombre d'IDE

L'indice correspondant est 30 pour 3, ou 10 pour 1 : il y a 10 enfants par IDE.
:::

## Proportion? Taux? Ratio? Indice?

::: {.callout-caution collapse="true" appearance="minimal"}

## Nombre de cancers cutanés / nombre de cancers 

[Proportion]{.cb}

- Une seule variable : le cancer
- Nombre de cancers = ensemble des cancers
- Les cancers cutanés sont un sous-ensemble des cancers

**C'est un rapport dans lequel le numérateur est inclut dans le dénominateur**

:::

::: {.callout-caution collapse="true" appearance="minimal"}
## Nombre de fumeurs / Nombre de non fumeurs

[Ratio]{.cb}

- Une seule variable : le statut tabagique
- Variable binaire : fumeur / non fumeur

**C'est un rapport entre les deux modalités d'une variable binaire**
:::

::: {.callout-caution collapse="true" appearance="minimal"}
## Consommation de cigarettes par habitant 

[Indice]{.cb}

- 2 variables :
  - Nombre de cigarettes
  - Nombre d'habitants
  
**C'est un rapport entre 2 effectifs différents**
:::

::: {.callout-caution collapse="true" appearance="minimal"}
## Nombre de décès sur une période / nombre de personnes à risque de décès sur cette période

[Taux]{.cb}

(la baignoire !)

:::

::: {.callout-caution collapse="true" appearance="minimal"}

## Nombre d'hypertendus en 1975 / nombre d'hypertendus en 1994 

[Indice]{.cb}

- 2 variables :
  - Nombre d'hypertendus sur une période
  - Nombre d'hypertendus sur une autre période
  
**C'est un rapport des effectifs 2 variables différents**

:::

::: {.callout-caution collapse="true" appearance="minimal"}
## Nombre d'amputés du bras / nombre d'amputés

[Proportion]{.cb}

- Une seule variable : l'amputation
- Nombre d'amputations = ensemble des amputations
- Les amputations du bras sont un sous-ensemble des amputations

**C'est un rapport dans lequel le numérateur est inclut dans le dénominateur**
:::


## Critères de qualité d'un indicateur

Pour être de qualité, un indicateur de santé doit être :


#### Simple et acceptable {.unnumbered}

Facilement utilisable par les chercheurs, facilement compréhensible par les professionnels et les usagers.

::: callout-tip
## Le taux de mortalité infantile est une mesure simple et consensuelle du nombre d'enfants décédés entre la naissance et 12 mois, sur le nombre total de naissances vivantes dans une population donnée.
:::


#### Valide {.unnumbered}

La mesure a t-elle du sens, est-elle raccord à la réalité ?

::: callout-tip
## La mesure autonome de la pression artérielle (MAPA)
:::

#### Fiable {.unnumbered}

Si la mesure est répétée dans des conditions similaires, elle doit produire des résultats similaires. 

::: callout-tip
## La MAPA est également une mesure fiable, si on considère , (le matin à domicile)
:::

#### Sensible {.unnumbered}

La mesure détecte des petites changements dans le processus étudié.

::: callout-tip
## Un test de dépistage du cancer du sein doit être suffisamment sensible pour détecter une tumeur à un stade précoce, lorsque le traitement est le plus efficace.
:::

#### Spécifique {.unnumbered}

La mesure détecte uniquement le processus étudié

::: callout-tip
## Un test de dépistage du VIH doit être spécifique à l'infection à VIH et ne pas donner de résultats positifs pour d'autres infections virales.
:::


## Fiabilité vs validité {#sec-temp}

La validité est synonyme d'exactitude

La fiabilité est synonyme de précision


::: callout-tip
## exemple température, partie 1

:::


## Ce qu'il faut retenir

- [Reconnaitre les indicateurs de base]{.cb}
- [Distinguer fiabilité (précision) et validité (exactitude) : une mesure peut être fiable sans être valide !]{.cb}
