
::: callout-tip

Évolution de la connaissance (A) et de la part traitée et contrôlée (B) de l'hypertension artérielle (HTA) chez les personnes hypertendues entre ENNS 2006 et Esteban 2015, en fonction du sexe.

img hta

:::

################################33


### Pour mieux comprendre : la notion de personne-temps

La notion de [personne-temps]{.cb} peut paraître difficile à concevoir. 

Pour calculer un taux d'incidence, on ne regarde pas seulement combien de personnes développent la maladie, mais plutôt combien de personnes développent la maladie [en fonction du temps pendant lequel elles étaient à risque de développer la maladie]{.cb}.

Autrement dit, cela revient à [additionner]{.cb} tous les temps pendant lesquelles les personnes étaient à risque de devenir malades, jusqu'à ce qu'elles deviennent malades.

Le taux d'incidence correspond donc [au risque moyen de développer la maladie pendant la période considérée]{.cb}.


### Pour mieux comprendre : exemple

::: callout-warning
L'exemple suivant est là pour aider à la compréhension, il n'est pas attendu de savoir reproduire ce genre de calcul.
:::

[Exemple]


########################





